Румянцева Елизавета Ивановна КВБО-01-21

# 1.3.1 Задание
СОздать матрицу 8х8 и заполнить её в шахматном порядке нулями и единицами

In [2]:
import numpy as np
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 1.3.2 Задание
Создать 5х5 матрицу со значениям в строках от 0 до 4. Для создания необходимо использовать функцию arrange

In [4]:
import numpy as np
x = np.zeros((5,5))
print(x)
x += np.arange(5)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# 1.3.3 Задание
Создать массив 3x3x3 со случайными значениями.

In [5]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.98039893 0.32324522 0.77474913]
  [0.99124734 0.70892177 0.94913296]
  [0.28509611 0.3056153  0.48023926]]

 [[0.55069498 0.65658093 0.64084519]
  [0.36770385 0.302962   0.87139646]
  [0.02247916 0.73756478 0.60114327]]

 [[0.47173596 0.80779656 0.95170412]
  [0.46535999 0.03319642 0.02929463]
  [0.52954788 0.24380598 0.72048134]]]


# 1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах

In [8]:
x = np.zeros((5,5))
print(x)
for i in range(5):
    for j in range(5):
        if(i==0)or(j==0)or(i==4)or(j==4):
            x[i][j]=1
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [12]:
import random
m=10
numbers_list = [] 
for i in range(m):
    numbers_list.append(random.randint(3,9))
print(f'До сортировки: {numbers_list}') 
numbers_list.sort() 
print(f'После сортировки:  {numbers_list}') 

Before sorting: [4, 6, 4, 8, 4, 3, 4, 8, 5, 3]
After sorting:  [3, 3, 4, 4, 4, 4, 5, 6, 8, 8]


# 1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.

In [14]:
x = np.zeros((5,5))
print(x)
for i in range(5):
    for j in range(5):
        x[i][j]=random.randint(3,9)
print(x)
print(x.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[8. 7. 5. 9. 7.]
 [4. 4. 6. 9. 4.]
 [8. 8. 6. 7. 4.]
 [5. 7. 6. 8. 8.]
 [4. 8. 7. 7. 8.]]
(5, 5)


# 2.3.1 Задание
Найдитн евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [21]:
import pandas as pd
a = pd.Series([2, 4, 6, 8])
b = pd.Series([1, 3, 5, 7])
print(sum((a - b)**2)**.5)

2.0


# 2.3.2 Задание
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).


In [42]:
import pandas as pd

url="https://raw.githubusercontent.com/akmand/datasets/main/boston_housing.csv"
c=pd.read_csv(url)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
print(c)

       crim     zn  indus  chas    nox     rm    age     dis  rad  tax  \
0     0.006   18.0   2.31     0  0.538  6.575   65.2   4.090    1  296   
1     0.027    0.0   7.07     0  0.469  6.421   78.9   4.967    2  242   
2     0.027    0.0   7.07     0  0.469  7.185   61.1   4.967    2  242   
3     0.032    0.0   2.18     0  0.458  6.998   45.8   6.062    3  222   
4     0.069    0.0   2.18     0  0.458  7.147   54.2   6.062    3  222   
5     0.030    0.0   2.18     0  0.458  6.430   58.7   6.062    3  222   
6     0.088   12.5   7.87     0  0.524  6.012   66.6   5.560    5  311   
7     0.145   12.5   7.87     0  0.524  6.172   96.1   5.950    5  311   
8     0.211   12.5   7.87     0  0.524  5.631  100.0   6.082    5  311   
9     0.170   12.5   7.87     0  0.524  6.004   85.9   6.592    5  311   
10    0.225   12.5   7.87     0  0.524  6.377   94.3   6.347    5  311   
11    0.117   12.5   7.87     0  0.524  6.009   82.9   6.227    5  311   
12    0.094   12.5   7.87     0  0.524

# 2.3.3 Задания
## Проделайте с получившемся из предыдущего задания фреймом данных следующие действия
### 1)Вывести первые 3 строки с помощью метода head. 
### 2)Вывести последние 3 строки можно с помощью функции tail
### 3)Вывести количество строк и столбцов: dataframe.shape. 
### 4)Используя метод describe, мы можем получить описательную статистику для любых числовых столбцов.
### 5)Выберите индивидуальные данные или срезы фрейма данных
### 6)Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из людей старше 90

In [58]:
import pandas as pd
url="https://raw.githubusercontent.com/akmand/datasets/main/boston_housing.csv"
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
c=np.round(pd.read_csv(url),decimals=2)
print(c.head(3))
print(c.tail(3))
print("\n")
print(c.shape)
print("\n")
print(c.describe().round(2))
print("\n")
print(c.loc[1::500])
print("\n")
print(c[c['age']>99])

   crim    zn  indus  chas   nox    rm   age   dis  rad  tax  ptratio  bbtown  \
0  0.01  18.0   2.31     0  0.54  6.58  65.2  4.09    1  296     15.3  396.90   
1  0.03   0.0   7.07     0  0.47  6.42  78.9  4.97    2  242     17.8  396.90   
2  0.03   0.0   7.07     0  0.47  7.18  61.1  4.97    2  242     17.8  392.83   

   lstat  medv  
0   4.98  24.0  
1   9.14  21.6  
2   4.03  34.7  
     crim   zn  indus  chas   nox    rm   age   dis  rad  tax  ptratio  \
503  0.06  0.0  11.93     0  0.57  6.98  91.0  2.17    1  273     21.0   
504  0.11  0.0  11.93     0  0.57  6.79  89.3  2.39    1  273     21.0   
505  0.05  0.0  11.93     0  0.57  6.03  80.8  2.50    1  273     21.0   

     bbtown  lstat  medv  
503  396.90   5.64  23.9  
504  393.45   6.48  22.0  
505  396.90   7.88  11.9  


(506, 14)


         crim      zn   indus    chas     nox      rm     age     dis     rad  \
count  506.00  506.00  506.00  506.00  506.00  506.00  506.00  506.00  506.00   
mean     3.61   11.36   11

# 3.3.2 Задание
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [4]:
import pandas as pd
url="https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
c=pd.read_csv(url)
print(c.head(5))
def get_minmax(s):
    return (s-c['sepal_length_cm'].min())/(c['sepal_length_cm'].max()-c['sepal_length_cm'].min())
def zMethod(s):
    return (s-c.sepal_width_cm.mean())/c.sepal_width_cm.std()
c['sepal_length_cm']=c['sepal_length_cm'].apply(get_minmax)
c['sepal_width_cm']=c['sepal_width_cm'].apply(zMethod)
print(c.head(5))

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.028611              1.4             0.2  setosa
1         0.166667       -0.124540              1.4             0.2  setosa
2         0.111111        0.336720              1.3             0.2  setosa
3         0.083333        0.106090              1.5             0.2  setosa
4         0.194444        1.259242              1.4             0.2  setosa
